AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Recipe bot back-end stack.
Resources:
  RecipeRequestHandlerLogic:
    Properties:
      CodeUri: s3://recipe-bot-back-end/bot_back_end.zip
      Description: Lamda function to handle recipe requests.
      Handler: recipe_bot.handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 10
      Environment:
        Variables:
          AWS_YUMMLY_APP_ID:
          AWS_YUMMLY_APP_KEY: 
    Type: AWS::Serverless::Function